spring:
  config:
    activate:
      on-profile: stag

framework:
  datasource:
    mode: xa
    jndi:
      primary-name: java:comp/env/jdbc/corePrimary
      secondary-name: java:comp/env/jdbc/coreSecondary
