spring:
  application:
    name: framework-core
  messages:
    basename: common_message
    encoding: UTF-8
  profiles:
    active: local
  batch:
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:change-this-password}

framework:
  error:
    default-code: BIZ-0001
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
  file:
    base-dir: ./storage
  batch:
    cron: "0 0/5 * * * ?"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
